package architecture;

import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.core.importer.ImportOption.DoNotIncludeTests;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.methods;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.Architectures.layeredArchitecture;

/**
 * ArchUnit rules enforcing Bob's Onion 4-ring Clean Architecture.
 *
 * Generated by ddd-run init. This file is the harness's runtime enforcer:
 *   - Do NOT delete it.
 *   - You MAY add project-specific rules below.
 *   - Editing the existing rules means weakening the harness's guarantees.
 *
 * Adjust the package wildcards if your base package is not "com.example.ddd"
 * (search-replace "com.example.ddd" → "<your.base.package>").
 */
@AnalyzeClasses(
    packages = "com.example.ddd",
    importOptions = DoNotIncludeTests.class
)
public class CleanArchitectureTest {

    // -------- R7: 4-ring layered dependencies --------
    @ArchTest
    static final ArchRule layered_dependencies = layeredArchitecture()
        .consideringAllDependencies()
        .layer("domain").definedBy("..domain..")
        .layer("usecase").definedBy("..usecase..")
        .layer("adapter").definedBy("..adapter..")
        .layer("framework").definedBy("..framework..")
        .whereLayer("framework").mayNotBeAccessedByAnyLayer()
        .whereLayer("adapter").mayOnlyBeAccessedByLayers("framework")
        .whereLayer("usecase").mayOnlyBeAccessedByLayers("framework", "adapter")
        .whereLayer("domain").mayOnlyBeAccessedByLayers("framework", "adapter", "usecase");

    // -------- R3 + R9: domain layer is pure Java --------
    @ArchTest
    static final ArchRule domain_pure_of_frameworks = noClasses()
        .that().resideInAPackage("..domain..")
        .should().dependOnClassesThat().resideInAnyPackage(
            "org.springframework..",
            "jakarta.persistence..",
            "jakarta.inject..",
            "org.slf4j..",
            "lombok..");

    // -------- R3 + R9: usecase layer is pure Java POJO --------
    @ArchTest
    static final ArchRule usecase_pure_of_frameworks = noClasses()
        .that().resideInAPackage("..usecase..")
        .should().dependOnClassesThat().resideInAnyPackage(
            "org.springframework..",
            "jakarta.persistence..",
            "jakarta.inject..",
            "org.slf4j..",
            "lombok..");

    // -------- R8: @Transactional only in the decorator --------
    @ArchTest
    static final ArchRule transactional_methods_only_in_decorator = methods()
        .that().areAnnotatedWith(Transactional.class)
        .should().beDeclaredInClassesThat().haveFullyQualifiedName(
            "com.example.ddd.shared.framework.transaction.TransactionalUseCaseDecorator");

    @ArchTest
    static final ArchRule transactional_classes_only_in_decorator = classes()
        .that().areAnnotatedWith(Transactional.class)
        .should().haveFullyQualifiedName(
            "com.example.ddd.shared.framework.transaction.TransactionalUseCaseDecorator");

    // -------- R7: REST controllers may not import domain types --------
    @ArchTest
    static final ArchRule web_controller_no_domain = noClasses()
        .that().resideInAPackage("..adapter.web..")
        .should().dependOnClassesThat().resideInAPackage("..domain..");

    // -------- R5 + R7: repository implementations live in adapter.persistence --------
    @ArchTest
    static final ArchRule repository_impl_location = classes()
        .that().areAnnotatedWith(Repository.class)
        .should().resideInAPackage("..adapter.persistence..");

    // -------- R10: @EventListener only in adapter.messaging --------
    @ArchTest
    static final ArchRule event_listeners_only_in_messaging = methods()
        .that().areAnnotatedWith(EventListener.class)
        .should().beDeclaredInClassesThat().resideInAPackage("..adapter.messaging..");

    // -------- R10: domain event classes live in domain.events --------
    // NOTE: this rule assumes you define a marker interface
    //       `com.example.ddd.shared.domain.DomainEvent`. Once defined, replace
    //       this stub with:
    //
    //   @ArchTest static final ArchRule event_classes_in_domain = classes()
    //       .that().implement(DomainEvent.class)
    //       .should().resideInAPackage("..domain..events..");
    //
    // Until the marker exists this rule is a TODO-by-construction.
}
